version: '3'
services:
  db:
    image: postgres
    container_name: db
    env_file: .env

  web:
    build: .
    command: bundle exec "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    container_name: web
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
    links:
      #thứ tự start chứ k phải thứ tự hoàn thành
      - db

