version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER = webapp
      - POSTGRES_PASSWORD = 123456
  web:
    build: .
    command: rails s -b 0.0.0.0
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
    links:
      - db