default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #links rồi nên kết nối được
  host: <%= ENV['POSTGRES_URL'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  
development:
  <<: *default
  database: AlbumBlogManagement
test:
  <<: *default
  database: AlbumBlogManagement_test
production:
  <<: *default
  database: AlbumBlogManagement_production
  username: webapp
  password: <%= ENV['WEBAPP_DATABASE_PASSWORD'] %>
