# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Blog.create!(bcontent: 'Việc thất tình giống như thói quen đi ngủ muộn vậy. Khi còn trẻ, bạn giữ thói quen ấy rất lâu nhưng chỉ cần muốn thay đổi đều có thể bỏ được, có khi tốn nhiều thời gian để làm quen với việc đi ngủ sớm, nhưng cũng có khi chỉ vì một ngày quá mệt mỏi mà bất giác đi ngủ sớm và giữ thói quen ấy đến mãi sau này. Khi đó, bạn không biết quí trọng giấc ngủ mà chỉ thầm ước vào ngày hôm sau rằng giá như mình đi ngủ sớm hơn. Cũng tương tự như vậy, trong cuộc đời bình thường của mỗi con người, ai cũng sẽ phải trải qua dăm bảy lần thất tình. Nó cũng giống như việc bạn đi ngủ muộn vậy, có người bị chứng mất ngủ kinh niên, quanh năm suốt tháng trằn trọc khó ngủ, có người lại thích đi ngủ muộn, thỉnh thoảng một năm ngủ muộn một vài dịp chơi; nếu như bạn may mắn và sinh hoạt lành mạnh, điều độ thì cả đời bạn cũng không gặp cảnh mất ngủ bao giờ. Như tất cả mọi người đều biết, tác hại của việc thất tình và ngủ muộn hết sức nghiêm trọng và đáng lo ngại, về cơ bản thì chúng cũng có phần giống nhau bởi chúng không chỉ mang lại hậu quả xấu cho sức khoẻ mà còn có hại cho tim mạch và gây tổn thương cho não bộ. Vậy nguyên nhân để tạo ra việc thất tình hay thói quen ngủ muộn là gì? Đầu tiên, để nói về thất tình, nó là một trạng thái đau khổ từ quằn quại đến bâng quơ tuỳ theo cảm xúc của bệnh nhân. Người ta thất tình thường do ba lý do chính sau đây: không được yêu, được yêu nhưng rồi lại chia tay và một trạng thái gọi là chờ được yêu. Theo thực tế cho thấy, dân số chia đều cho mỗi loại thất tình với tỉ lệ 33,33%. Trong cuộc đời, xác suất để bạn gặp phải một trong số những tình trạng trên là 99,99%. Nếu như đến năm 80 tuổi mà bạn chưa gặp được một trường hợp nào trong đó thì chúc mừng bạn đã nằm trong con số 0,001% còn lại và là người hạnh phúc nhất thế giới mà chẳng cần phải đến Đan Mạch. Còn nếu như bạn đang ở Đan Mạch rồi thì bạn sẽ được nhân đôi sự may mắn đấy! Nguyên nhân để tạo ra việc thất tình có thể coi là điều kiện cần và đủ để tạo ra việc mất ngủ. Còn nguyên nhân của việc mất ngủ thì nhiều vô số kể, đây không phải là một bài nghiên cứu về sức khoẻ nên xin các bạn hãy tra Google để biết thêm chi tiết. Thế thì, vấn đề ở đây là gì? Đó là tất cả mọi người đều hiểu được tác hại của việc ngủ muộn cũng như thất tình nhưng họ vẫn cứ tiếp tục làm như vậy hàng ngày, hàng tháng, cho đến hết hoặc gần hết tuổi trẻ của mình, đôi khi là đến tận khi họ già rồi. Đến một ngày nào đó, khi cơ thể và lý trí đã trở nên mỏi mệt, không còn sức lực để chống chọi với những cơn đau đầu hoặc đau tim ấy nữa, chúng ta sẽ tự biết yêu thương bản thân, yêu thương sức khoẻ và sẽ tự cân bằng lại chính mình. ', blogPic: '/blog_avatar/1.jpg', writer: 1, viewNumber: 5)
Blog.create!(bcontent: 'Càng sống nhiều ta càng thấy cái chết dễ dàng đến với bất cứ một ai. Chết quá dễ mà sống thì quá khó. Hôm qua gặp nhau đấy, ngày mai lại mất nhau. Sống thì có hẹn hò hôm nay hôm mai. Chết thì chẳng bao giờ có một cuộc hẹn hò nào trước. Một buổi sáng cách đây bốn năm, lúc tôi đang ngồi uống rượu với bạn, mẹ tôi bảo: “Mạ đi chơi chút nghe”. Thế rồi một giờ sau tôi được điện thoại báo tin mẹ tôi đã mất tại nhà người bạn. Càng yêu ta càng thấy: có tình yêu thì khó mà mất tình thì quá dễ. Hôm qua mới yêu nhau đấy, hôm nay đã mất rồi. Mất sạch như người đi buôn mất hết vốn liếng. Cứ tự an ủi mình khi nghĩ rằng mình đau khổ thì có một kẻ khác đang hạnh phúc. Và biết đâu cái thời gian mình được yêu thì một người khác cũng đang đau khổ vô cùng. Nghĩ thế thì thấy cuộc đời bỗng nhẹ nhàng hơn và cũng dễ tha thứ cho nhau. Sống mà giữ mãi trong lòng những hờn oán thì cũng nặng nề. Có người bỏ cuộc đời mà đi như một giấc ngủ quên. Có người bỏ cuộc tình mà đi như người đãng trí. Dù sao cũng đã lãng quên một nơi này để đi về một chốn khác. Phụ đời và phụ người hình như cũng vậy mà thôi. Người ở lại bao giờ cũng nhớ thương một hình bóng mình đã mất. Khó mà quên nhanh, khó mà xóa đi trong lòng một nỗi ngậm ngùi. Tưởng rằng có thể quên dễ dàng một cuộc tình nhưng hóa ra chẳng bao giờ quên được. Mượn cuộc tình này để xóa cuộc tình kia chỉ là một sự vá víu cho tâm hồn. Những mảnh vá ấy chỉ đủ để làm phẳng lặng bên ngoài mà thôi. Mỗi một con người vì ngại chết mà muốn sống. Mỗi một con người vì sợ mất tình mà giữ mãi một lòng nhớ nhung. Cuối cùng thì lòng yêu thương cuộc sống cũng không giữ lại đời người. Cuối cùng thì tình yêu không giữ được người mình yêu…', blogPic: '/blog_avatar/2.jpg', writer: 2, viewNumber: 2)
Blog.create!(bcontent: 'Đôi lúc những lời hỏi thăm vào những giai đoạn mệt mỏi, nhạy cảm lại khiến người mình thương không thoải mái, tức giận. Đã không giúp được cô ấy thư giãn còn làm chuyện tệ hơn các cậu à... Cô gái ấy mạnh mẽ nhưng bên trong có yếu đuối, tuổi thơ có ít sự thương yêu hơn những đứa trẻ khác ~cryinnight~. Càng làm tôi thấy muốn được chở che cho cô ấy hơn, khiến động lực sống càng mạnh mãnh hơn. Nam nhi đầu đội trời chân đạm đất vậy không sợ gì vậy mà lắm lúc mềm nhũn khi đứng trước người mình thương', blogPic: '/blog_avatar/3.jpg', writer: 3, viewNumber: 3)
Blog.create!(bcontent: 'Trời ơi thật mệt mỏi', blogPic: '/blog_avatar/4.jpg', writer: 1, viewNumber: 4)

User.create!(email:'thanh@gmail.com', pass:'123', tell:'456')
User.create!(email:'phuong@gmail.com', pass:'123', tell:'456')
User.create!(email:'thanh@gmail.com', pass:'123', tell:'456')

Album.create!(title:'Thiên nhiên', acontent:'Thiên vô tận ơi là vô tận :v', viewNumber: 3, creator: 2)
Album.create!(title:'Động vật', acontent:'Thế giới động vật bao la', viewNumber: 3, creator: 1)
Album.create!(title:'Mùa xuân', acontent:'Xuân về bao hóa lá', viewNumber: 3, creator: 2)
Album.create!(title:'Nắng', acontent:'Nắng quá thôi bỏ đi', viewNumber: 3, creator: 1)
Album.create!(title:'Mưa', acontent:'Mưa lạnh, mưa buồn mưa nhớ ai', viewNumber: 3, creator: 2)
Album.create!(title:'Mùa hè', acontent:'Hè về nóng bức phượng nở, học sinh nghỉ hè', viewNumber: 3, creator: 2)


Picture.create!(viewNumber:0, uploader:1, albumID:1)
Picture.create!(viewNumber:0, uploader:2, albumID:2)
Picture.create!(viewNumber:0, uploader:2, albumID:3)
Picture.create!(viewNumber:0, uploader:1, albumID:4)
Picture.create!(viewNumber:0, uploader:2, albumID:5)
Picture.create!(viewNumber:0, uploader:1, albumID:6)